### PR TITLE
CHARTS-541 Add onBodyRowMouseEnter/Leave to <SortableTable>

### PR DESCRIPTION
**Pull request by pzrq**
This PR adds two new event handlers to the `<SortableTable>` component:

- `onBodyRowMouseEnter`
- `onBodyRowMouseLeave`

I have tested them in Charts by:
1. Manually copying the updated `hadron-react/packages/hadron-react-components/lib/sortable-table.js` into the `node_modules/hadron-react-components/lib/sortable-table.js` of charts ([npm link](https://docs.npmjs.com/cli/link) may also work but it's been unreliable for me in the past, I've tended to use pre-release versions as needed, for example I intend to use [`lerna --canary`](https://github.com/lerna/lerna#--canary--c) after this though may also ping @durran depending on how events pan out)
2. Add a [`debugger`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)
3. (If necessary) check out a relevant older version of Charts, such as `85e1ae904c064de2bb9cf1705cc09c41831e3133`
4. `charts$ npm run build:dll; npm start`

I then get:

testing against older version works for me

This PR also adds appropriate enzyme tests, performs a few [variable renames to improve readability by avoiding mental mapping](https://github.com/ryanmcdermott/clean-code-javascript#avoid-mental-mapping), and package-lock.json / updates the lib files of hadron-react-bson from my following of the README.md.

Please read the individual commit messages below for more details.

### CODE REVIEW

**Review by matt-d-rat — APPROVED** [review]
LGTM 👍 @pzrq you may wish for @durran to take a look at these changes to evaluate any potential impact on Compass.

From my point of view I can't see that there would be, but definitely worth putting it on his radar.

**Comment by pzrq** [comment]
Not merging yet as I'm not actually convinced this will help solve the higher level problem of an entire table row being the `BaseComponent` in a hoverable context, and the editable button being the `LayerComponent` in a hoverable context, or if a different paradigm might be needed.

**Comment by durran** [comment]
No impact on Compass here - the new props aren't required so we're fine.

**Comment by pzrq** [comment]
@satyasinha and I got CHARTS-541 working with just this PR so I'm going to merge now. 

Thanks @matt-d-rat @durran 👍

**Comment by pzrq** [comment]
Hmm, I think I'm running into https://github.com/lerna/lerna/issues/1137

**Comment by pzrq** [comment]
Yep, published as `1.13.1-0` for now (which is also wrong as lerna's menu should have given me a `1.13.0-1`, option but I didn't see that so that's another issue at some point...).

**Comment by pzrq** [comment]
Finally published in [`v1.13.1`](https://github.com/mongodb-js/hadron-react/releases/tag/v1.13.1).

**Pull request merged**
